.github/workflows/acceptancetest-analyze.yml
.github/workflows/unittest-analyze.yml
build.gradle
gradle.properties
gradle/sonar.gradle
settings.gradle

sonar cloud, 단위테스트, CI를 추가했습니다.
- closes #4 
https://docs.sonarcloud.io/getting-started/github/

chore: `sonarcloud`, `CI` 추가

---

coverage-exclude.asap
src/main/java/shop/woowasap/asap/app/Application.java
src/main/java/shop/woowasap/asap/auth/domain/User.java
src/main/java/shop/woowasap/asap/shop/domain/Order.java
src/main/java/shop/woowasap/asap/shop/domain/Product.java
src/main/java/shop/woowasap/asap/shop/domain/User.java
src/main/java/shop/woowasap/asap/shop/domain/UserType.java

feat: 도메인 및 패키지 구조 스캐폴딩

---

build.gradle
gradle/jacoco.gradle
gradle/junit.gradle
gradle/lombok.gradle
gradle/sonar.gradle
gradle/spring.gradle
lombok.config
settings.gradle
support/.gitignore
support/jacoco/.gitignore

gradle 세팅을 multi-module에 맞게 수정했습니다.
- resolve #12 
[java-library](https://docs.gradle.org/current/userguide/java_library_plugin.html)

refactor: `gradle 세팅을 multi-module` 맞게 수정한다

---

.github/workflows/acceptancetest-analyze.yml
.github/workflows/unittest-analyze.yml
app/.gitignore
app/src/main/java/shop/woowasap/Application.java
settings.gradle

app 모듈을 추가하고 unit-test-ci에서 인수테스트를 제거했습니다.
- resolve #12

refactor: `app 모듈을 추가`및 unit-test-ci에서 인수테스트를 제거

---

app/src/main/java/shop/woowasap/Application.java
settings.gradle

`settings.gradle`의 rootProject.name 변경했습니다.
- closes #21

chore: `settings.gradle`의 rootProject.name 변경

---

app/build.gradle
app/src/test/java/shop/woowasap/BeanScanBaseLocation.java
app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/valid/AuthValidator.java
app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
app/src/test/java/shop/woowasap/mock/dto/LoginRequest.java
app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
app/src/test/java/shop/woowasap/mock/dto/RegisterProductRequest.java
app/src/test/java/shop/woowasap/mock/dto/SignUpRequest.java
app/src/test/java/shop/woowasap/mock/dto/SignUpResponse.java
app/src/test/java/shop/woowasap/mock/dto/UpdateProductRequest.java

인수테스트 관련 템플릿을 추가했습니다.
- close : #29

test: 인수테스트 템플릿 추가

---

.github/workflows/infer-analyze.yml
app/build.gradle
app/src/test/java/shop/woowasap/BeanScanBaseLocation.java
app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
app/src/test/java/shop/woowasap/accept/AuthAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/valid/AuthValidator.java
app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
app/src/test/java/shop/woowasap/mock/dto/LoginRequest.java
app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
app/src/test/java/shop/woowasap/mock/dto/RegisterProductRequest.java
app/src/test/java/shop/woowasap/mock/dto/SignUpRequest.java
app/src/test/java/shop/woowasap/mock/dto/SignUpResponse.java
app/src/test/java/shop/woowasap/mock/dto/UpdateProductRequest.java

test: 회원가입 인수테스트 작성

---

Dockerfile-Infer
app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
app/src/test/java/shop/woowasap/mock/dto/LoginResponse.java

상품 등록 인수테스트를 작성했습니다.
- resolve #26

test: 상품 등록 인수테스트 작성

---

Dockerfile-Infer
app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
app/src/test/java/shop/woowasap/mock/dto/LoginResponse.java

상품 수정 인수테스트를 작성했습니다.
- resolve #27

test: 상품수정 인수테스트 작성

---

.github/workflows/infer-analyze.yml
Dockerfile-Infer
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/Password.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/User.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/UserId.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/AuthDomainBaseException.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/DuplicatedUserIdException.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/PasswordValidateException.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/UserIdValidateException.java
auth/auth-domain/src/test/java/shop/woowasap/auth/domain/PasswordTest.java
auth/auth-domain/src/test/java/shop/woowasap/auth/domain/UserIdTest.java
auth/auth-domain/src/test/java/shop/woowasap/auth/domain/UserTest.java

유저 도메인을 생성하였습니다.
- resolve #25

feat: 유저 도메인 생성

---

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/fixture/ProductDtoFixture.java
app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
app/src/test/java/shop/woowasap/mock/dto/ProductResponse.java

test: 특정 상품 조회 인수테스트를 작성한다

---

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/fixture/ProductDtoFixture.java
app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
app/src/test/java/shop/woowasap/mock/dto/ProductResponse.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/Product.java
shop/shop-service/build.gradle
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/dto/ProductResponse.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/exception/CannotFindProductException.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/repository/ProductRepository.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/support/valid/ProductValidator.java

productId로 product를 조회하는 기능을 추가했습니다.
- resolve #46

feat: productId로 Product 조회 기능 추가

---

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
app/src/test/java/shop/woowasap/mock/dto/RegisterProductRequest.java
shop/shop-domain/build.gradle
shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
shop/shop-repository/build.gradle
shop/shop-service/build.gradle
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/dto/RegisterProductRequest.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/repository/ProductRepository.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java

상품 등록 관련 서비스 계층을 구현했습니다.
- resolve #26

feat: 상품 등록 서비스 구현

---

coverage-exclude.asap
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java

상품 등록 컨트롤러를 구현했습니다.
- resolve #26

feat: 상품 등록 컨트롤러 구현

---

coverage-exclude.asap
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java

productController 를 개발했습니다.
- resolve #46

feat: `/products/details/{product-id}` API Controller 개발

---

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java

- 상품 수정 요청 url에 admin을 추가하였고, 로그인 인증 관련 test를 제거했습니다.
- resolve #27

fix: 상품 수정 기능 admin 추가 및 인가 test 제거

---

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java

어드민 상품 전체 조회 시 인수테스트를 작성했습니다.
- resolve #28

test: 어드민 상품 전체 조회 인수테스트 작성

---

shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java

- 상품 전체 조회 컨트롤러를 구현한다
- resolve #31

feat: 상품 전체 조회 컨트롤러를 구현한다

---

shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductUseCase.java
shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/ProductRepository.java
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java

어드민 상품 상세 조회 서비스 구현했습니다.
- resolve #55

feat: 어드민 상품 상세 조회 서비스 구현

---

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductUseCase.java
shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/ProductRepository.java
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java

어드민 상품 상세 조회 기능을 구현했습니다.
- close #55

feat: 상품 상세 조회 - 어드민

---

app/src/test/java/shop/woowasap/accept/AuthAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/valid/AuthValidator.java
app/src/test/java/shop/woowasap/mock/dto/SignUpRequest.java

feat: 로그인 인수테스트 추가

---

order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java
order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidOrderProductException.java
order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidPriceException.java
order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidQuantityException.java
order/order-domain/src/test/java/shop/woowasap/order/domain/OrderProductTest.java
order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderFixture.java
order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderProductFixture.java

Order 도메인을 생성했습니다.
- resolve #57

feat: Order 모듈의 도메인 생성

---

app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/CartApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/fixture/CartFixture.java
app/src/test/java/shop/woowasap/accept/support/valid/CartValidator.java
app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java

- 장바구니 상품 조회 기능 인수테스트를 작성했습니다.
- resolve #61

test: 장바구니 상품 조회 인수테스트 작성

---

app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/CartApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/fixture/CartFixture.java
app/src/test/java/shop/woowasap/accept/support/valid/CartValidator.java

장바구니에 상품을 추가하는 인수테스트를 작성했습니다.
- resolve #60

test: 장바구니 상품 추가 인수테스트 작성

---

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
app/src/test/java/shop/woowasap/mock/dto/OrderProductRequest.java
coverage-exclude.asap
order/order-controller/build.gradle
order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
order/order-controller/src/main/java/shop/woowasap/order/controller/request/OrderProductQuantityRequest.java
settings.gradle

OrderController를 추가했습니다.
- resolve #57

feat: `POST /v1/orders/products/{product-id}` handler 추가

---

order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductConnector.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductConnectorService.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductConnectorServiceTest.java

ProductConnectorService가 prodcutId에 해당하는 Product를 반환하도록 수정
- resolve #57

feat: ProductConnectorService 구현

---

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
app/src/test/java/shop/woowasap/mock/dto/OrderProductResponse.java
app/src/test/java/shop/woowasap/mock/dto/OrderResponse.java
app/src/test/java/shop/woowasap/mock/dto/OrdersResponse.java
app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java

구매내역을 전체조회하는 인수테스트를 작성했습니다.
- resolve #59

test: 구매내역 전체 조회 인수테스트 생성

---

order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java

`/v1/orders?page&size` handler를 추가했습니다.
- resolve #59

feat: `/v1/orders?page&size` handler 추가

---

app/src/test/java/shop/woowasap/accept/support/valid/CartValidator.java
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java

- 장바구니 상품 조회 컨트롤러를 만들었습니다.
- resolve #61

feat: 장바구니 상품 조회 컨트롤러

---

app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/spi/CartRepository.java
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java

장바구니 상품 등록 컨트롤러 구현했습니다.
- resolve #60

feat: 장바구니 상품 등록 컨트롤러 구현

---

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Cart.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/NotExistsCartProductException.java
shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java

장바구니 상품 수량 수정 도메인 기능을 구현했습니다.
- resolve #62

feat: 장바구니 상품 수량 수정 도메인 기능 구현

---

shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java

장바구니 상품 수량 수정 컨트롤러를 구현했습니다.
- resolve #62

feat: 장바구니 상품 수량 수정 컨트롤러 구현

---

coverage-exclude.asap
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/ProductEntity.java

- Product Entity 기능을 구현했습니다.
- resolve #147

feat: Product Entity 기능 구현

---

shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/jpa/ProductJpaRepository.java

- Product repository 기능을 구현했습니다.
- resolve #147

feat: Product repository 기능 구현

---

coverage-exclude.asap
order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java
order/order-domain/src/main/java/shop/woowasap/order/domain/exception/BlankProductNameException.java
order/order-domain/src/test/java/shop/woowasap/order/domain/OrderProductTest.java
order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderProductFixture.java
order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderProductFixture.java

OrderProduct 도메인에 name 필드를 추가했습니다.
- resolve #159

refactor: `OrderProduct` 도메인에 name 필드 추가

---

shop/shop-repository/src/main/java/shop/woowasap/shop/repository/CartRepositoryImpl.java
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/CartEntity.java
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/jpa/CartJpaRepository.java
shop/shop-repository/src/test/java/shop/woowasap/BeanScanBaseLocation.java
shop/shop-repository/src/test/java/shop/woowasap/shop/repository/CartRepositoryImplTest.java

Cart repository 기능을 구현했습니다.
- resolve #146

feat: CartRepository 기능 구현

---

app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/LoginUser.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/TokenProvider.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/AuthenticationProvider.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/JwtTokenProvider.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebConfiguration.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/resolver/AuthArgumentResolver.java
auth/auth-infra/src/test/java/shop/woowasap/auth/infra/AuthenticationProviderTest.java
auth/auth-infra/src/test/java/shop/woowasap/auth/infra/JwtTokenProviderTest.java

`@LoginUser`를 사용하는 AuthArgumentResolver를 추가했습니다.
- resolve #167

feat: AuthArgumentResolver 추가

---

app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/LoginUser.java
auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/TokenProvider.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/AuthenticationProvider.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/JwtTokenProvider.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebConfiguration.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/resolver/AuthArgumentResolver.java
auth/auth-infra/src/test/java/shop/woowasap/auth/infra/AuthenticationProviderTest.java
auth/auth-infra/src/test/java/shop/woowasap/auth/infra/JwtTokenProviderTest.java

유저 아이디 ArgumentResolver 추가했습니다.

feat: 유저 아이디 ArgumentResolver 추가

---

order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
order/order-domain/src/main/java/shop/woowasap/order/domain/OrderType.java
order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntity.java
order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntityType.java

Domain 과 Entity 에 주문의 상태를 추가했습니다.
- resolve #196

refactor: Domain 과 Entity 에 주문의 상태 추가

---

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderEventConsumer.java
order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PayFailEvent.java
order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PaySuccessEvent.java
order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/PayFailEvent.java
order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/StockSuccessEvent.java
order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java
order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
order/order-service/src/test/java/shop/woowasap/order/service/OrderEventServiceTest.java

`OrderEventService` 를 생성했습니다.
- resolve #196

feat: `OrderEventService` 생성

---

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
order/order-domain/src/main/java/shop/woowasap/order/domain/OrderType.java
order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderEventConsumer.java
order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PayFailEvent.java
order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PaySuccessEvent.java
order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderIdResponse.java
order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/PayFailEvent.java
order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/StockSuccessEvent.java
order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntity.java
order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntityType.java
order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java
order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
order/order-service/src/test/java/shop/woowasap/order/service/OrderEventServiceTest.java
order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java

주문기능을 비동기 이벤트 기반으로 변경했습니다.
- close #196

refactor: 주문 기능 비동기 이벤트 기반으로 변경

---

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/ProductModificationPermissionException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java
shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
shop/shop-repository/src/test/java/shop/woowasap/shop/repository/support/ProductFixture.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductConnectorServiceTest.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/CartFixture.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java

- 현재 판매중인 상품의 수정을 요청할 경우 예외를 발생시키는 기능을 구현했습니다.
- close #176

feat: 현재 판매 중인 Product 는 수정 불가능

---

app/build.gradle
app/src/main/java/shop/woowasap/advice/GlobalExceptionHandler.java
app/src/main/resources/application.yml
app/src/main/resources/logback-spring.xml
auth/auth-controller/src/main/java/shop/woowasap/auth/controller/AuthController.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/resolver/AuthArgumentResolver.java
auth/auth-infra/src/test/java/shop/woowasap/auth/infra/AuthenticationProviderTest.java
auth/auth-infra/src/test/java/shop/woowasap/auth/infra/JwtTokenProviderTest.java
auth/auth-repository/src/test/java/shop/woowasap/auth/repository/UserRepositoryImplTest.java
gradle.properties
payment/payment-controller/src/main/java/shop/woowasap/payment/controller/PayController.java

Sentry를 연결했습니다.
- close #218 
[ASAP sentry project](https://asap-3028fecc7.sentry.io/projects/asap-sentry/?project=4505740445286401)

chore: `Sentry Connect`

---

.github/workflows/docker-image-build.yml
Dockerfile
app/build.gradle

도커 이미지로 빌드하는 Workflow를 추가했습니다.
- close #220

chore: 도커 이미지 빌드, workflow 추가

---

.github/workflows/docker-image-build.yml
Dockerfile

chore: 환경변수 설정 추가

---

app/build.gradle
app/src/main/resources/application-prod.yml
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java

Spring boot actuator와 관련된 설정을 추가했습니다.
- resolve #228

chore: Spring boot actuator와 모니터링 툴 부착

---

.github/workflows/docker-image-build.yml

docker-image build yml 에서 platform 삭제
- close #230

fix: docker-image build yml파일 수정

---

payment/payment-domain/src/main/java/shop/woowasap/payment/domain/exception/DoesNotFindOrderException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/CartException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductDescriptionException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductNameException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductPriceException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductQuantityException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductSaleDurationException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductStartTimeException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/ProductException.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Description.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Name.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Price.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Quantity.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/SaleTime.java

feat: 예외 메시지를 추가

---

auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java

fix: CORS 패턴으로 수정

---

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
order/order-domain/src/main/java/shop/woowasap/order/domain/OrderType.java

주문취소 인수테스트를 작성했습니다.
- resolve #255

test: 주문취소 인수테스트 작성

---

app/src/main/resources/application-dev.yml
app/src/main/resources/application-prod.yml
app/src/test/resources/application.yml
order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntity.java
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/CartEntity.java

`batchSize` 와 `default batchsize` 를 10으로 설정했습니다
- close #266

refactor: `batchSize` 와 `default batchsize` 10으로 설정

---

.github/workflows/deploy.yml
.github/workflows/docker-image-build.yml

chore: Self hosted runner를 사용해서 배포하도록 CD를 추가했습니다.
- close #237

chore: Self hosted runner를 사용해서 배포하도록 수정

---

app/src/main/resources/db/migration/V1__init.sql
app/src/main/resources/db/migration/V2__index.sql
shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/ProductEntity.java

- check 제약 조건과 인덱스 설정
- close #275

fix: check 제약 조건과 인덱스 설정

---

app/build.gradle
app/src/main/java/shop/woowasap/config/RedisConfig.java
app/src/main/resources/application-dev.yml
app/src/main/resources/application-prod.yml
app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
app/src/test/java/shop/woowasap/accept/AcceptanceTestConfiguration.java
app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
app/src/test/resources/application.yml
auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java
shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/response/ProductResponse.java
shop/shop-service/build.gradle
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/config/ShopCacheConfig.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java

feat: cache 설정 추가

---

.github/workflows/deploy.yml
.github/workflows/docker-image-build.yml

gradle build action 버전을 수정했습니다.
- close #250

fix: gradle build action 버전 수정

---

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProductQuantity.java
shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java
shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java

release: `v1.1.2`
