.github/workflows/acceptancetest-analyze.yml, build.gradle, gradle/jacoco.gradle
테스트 커버리지에 제외된 클래스가 test report에 그대로 노출되는 버그 수정
- closes #6
=> fix: 테스트 커버리지에 제외된 클래스가 test report에 그대로 노출되는 버그 수정

.github/workflows/type-labeler.yml
Github PR , Issue에 기능단위로 자동으로 라벨을 붙인다
- closes #10 
`https://gitmoji.dev` 참조해서 설정했는데, 바꾸고싶은 이모지 있으시면 commet 남겨주세요
=> chore: PR, Issue기능단위로 자동으로 라벨 붙이는 기능 추가

coverage-exclude.asap
coverage-exclude.asap 경로를 모듈에 맞게 수정했습니다.
- resolve #12
=> refactor: coverage-exclude.asap 경로를 모듈에 맞게 수정

app/build.gradle, app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java, app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java, app/src/test/java/shop/woowasap/mock/dto/LoginRequest.java, app/src/test/java/shop/woowasap/mock/dto/RegisterProductRequest.java, app/src/test/java/shop/woowasap/mock/dto/SignUpRequest.java, app/src/test/java/shop/woowasap/mock/dto/UpdateProductRequest.java
auth, shop api의 인수테스트 API supporter를 추가했습니다.
**나중에, dto구현할때 mock.dto 구조 그대로 가져가서 사용하시거나, 직접 만드신 dto로 import 변경해주세요**
- resolve #29
=> test: auth, shop `인수테스트 API supporter 추가`

app/build.gradle, app/src/test/java/shop/woowasap/BeanScanBaseLocation.java, app/src/test/java/shop/woowasap/accept/AcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/valid/AuthValidator.java, app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java, app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java, app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java, app/src/test/java/shop/woowasap/mock/dto/SignUpResponse.java
auth, shop 인수테스트의 validator를 추가했습니다.
**나중에, dto구현할때 mock.dto 구조 그대로 가져가서 사용하시거나, 직접 만드신 dto로 import 변경해주세요**
``` java
// 사용예시
class ShopAcceptanceTest extends AcceptanceTest {
// ...
}
```
- resolve #29
=> test: auth, shop `인수테스트의 validator 추가`

Dockerfile-Infer
Infer CI에서 accept test 를 제외했습니다.
- close #38
=> fix: Infer CI 에서 `accept test` 제외

auth/auth-service/build.gradle, core/id-gen/build.gradle, core/id-gen/src/main/java/shop/woowasap/core/id/api/IdGenerator.java, core/id-gen/src/main/java/shop/woowasap/core/id/snowflake/SnowflakeIdGenerator.java, core/id-gen/src/test/java/shop/woowasap/core/id/snowflake/SnowflakeIdGeneratorTest.java, settings.gradle, shop/shop-service/build.gradle
**Snowflake Id generator** 를 부착했습니다.
구현체는 Tsid 인데, 그냥 snowflake 알고리즘을 구현한거라 통용되는 snowflake로 부를게요!
**Snowflake?**
```
(___________) (______) (__________)
( timestamp ) ( node ) (sequential)
```
로 이루어져있고, node를 장비의 고유번호 (혹은 우리가 지정) 해서 서버 혹은 스레드마다 다른 값이 생성됨을 보장합니다. 
멀티스레드에서 이거보다 좋은 id 생성기를 찾지는 못했는데, 찾으면 추후에 변경하면 될거같아요. 
추상화 해놔서 구현체만 갈아치우면 됩니다!
(1024, 4096 까지 가능은 한데, 그럼 성능이 내려가서 256으로 만들었습니다. 나중에 저희 서비스가 동접 256뚫으면 늘리면 될듯 합니다)
_이 부분은 테스트 참조해주세요_
- close #30 
[snowflake?](https://en.wikipedia.org/wiki/Snowflake_ID)
=> feat: snowflake id generator 생성

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java, app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
존재하지 않는 상품에 대한 수정을 요청할 경우의 테스트를 추가했습니다.
- resolve #27
=> test: 상품 수정 인수테스트 수정 및 추가

app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
ShopValidator의 softAssertions이 잘못 사용되고있는부분 수정했습니다.
- resolve #46
=> fix: ShopValidator의 softAssertions 수정

.github/workflows/infer-analyze.yml
Infer CI가 main, develop, release로 가는 PR에만 수행되도록 수정했습니다.
- close #67
=> chore: `Infer CI` 가 main, develop release PR 에서만 수행되도록 수정

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java, app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java, app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java, shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/response/ProductResponse.java
특정 상품 조회 인수테스트를 추가했습니다.
- resolve #46
=> test: 특정 상품 조회 인수테스트를 추가한다

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
`/products/{product-id}` API handler를 추가했습니다.
- resolve #46
=> feat: `/products/{product-id}` API handler 추가

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java, app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
- 상품 전체 조회 인수테스트를 작성했습니다.
- resolve #31
=> test: 상품 전체 조회 인수테스트

app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
상품 상세 조회 어드민인 경우 인수테스트를 작성했습니다.
- resolve #55
=> test: 어드민 상품 상세 조회 인수테스트 작성

shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
어드민 상품 상세 조회 컨트롤러를 구현했습니다.
- resolve #55 
- `ProductAdminController` 에서 `readProductsInAdmin`, `readProductInAdmin` 메서드에서 Admin 인 경우임을 메서드 명에서 명시하고 있는데, 이제는 `ProductAdminController`로 Admin 전용 컨트롤러임을 명시하므로 `InAdmin` 를 없애도 괜찮지 않을까요?
- 일단은 붙여 놨는데, 혹시 다른 분들은 어떤 생각이실지 궁금해요!
=> feat: 어드민 상품 상세 조회 컨트롤러 구현

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java, app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java, app/src/test/java/shop/woowasap/mock/dto/OrderProductRequest.java, settings.gradle
상품 구매 인수테스트를 추가했습니다.
- resolve #57
=> test: 상품 구매 인수테스트 추가

.gitignore, app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java, app/src/test/java/shop/woowasap/mock/dto/OrderProductRequest.java, coverage-exclude.asap, order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java, order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java, order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotOrderedException.java, order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidProductSaleTimeException.java, order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidQuantityException.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/request/OrderProductRequest.java, order/order-domain/src/main/java/shop/woowasap/order/domain/out/OrderRepository.java, order/order-domain/src/main/java/shop/woowasap/order/domain/out/Payment.java, order/order-domain/src/test/java/shop/woowasap/order/domain/OrderProductTest.java, order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderFixture.java, order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderProductFixture.java, order/order-service/build.gradle, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java, order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java, order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/ProductFixture.java, shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductConnector.java
상품 단일 구매 서비스를 추가했습니다.
- resolve #57
=> feat: 상품 단일 구매 서비스 추가

coverage-exclude.asap, order/order-infra/build.gradle, order/order-infra/src/main/java/shop/woowasap/order/payment/random/RandomOrderPayment.java, settings.gradle
0~1초뒤 true를 반환하는 RandomOrderPayment 생성
- resolve #57
=> feat: 0~1초 뒤 성공을 반환하는 RandomOrderPayment 생성

order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java, order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
Order 도메인에 createdAt을 추가했습니다.
- resolve #59
=> feat: Order 도메인에 createdAt 추가

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderProductResponse.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderResponse.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrdersResponse.java, order/order-domain/src/main/java/shop/woowasap/order/domain/out/OrderRepository.java, order/order-domain/src/main/java/shop/woowasap/order/domain/out/response/OrdersPaginationResponse.java, order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java, order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java, order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java, order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderFixture.java, order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderProductFixture.java
OrderService.getOrderByUserId 메소드를 추가했습니다.
- resolve #59
=> feat: OrderService.getOrderByUserId 추가

order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
MockOrderRepository의 findAllOrderByUserId를 구현했습니다.
- resolve #59
=> feat: MockOrderRepository.findAllOrderByUserId 구현

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java, app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java, app/src/test/java/shop/woowasap/mock/dto/DetailOrderProductResponse.java, app/src/test/java/shop/woowasap/mock/dto/DetailOrderResponse.java
특정 주문 내역을 조회하는 인수테스트를 추가했습니다.
- resolve #56
=> test: 특정 Order 조회 인수테스트 추가

order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
MockOrderRepository를 구현했습니다.
- resolve #56
=> feat: MockOrderRepository 구현

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java, order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderProductResponse.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderResponse.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java, order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java, order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
전체 상품 조회 API의 응답 body를 변경했습니다.
``` json
{
"orders" : [
{
"orderId" : "number",
"products" :[ {
"productId" : "number",
"name" : "string"
}],
"price" : "number",
"quantity" : "number",
"createdAt":  "string",
}
],
"page" : "number",
"totalPage" : "number"
}
```
``` json
{
"orders" : [
{
"orderId" : "number",
"products" :[ {
"productId" : "number",
"name" : "string",
"price": "number",
"quantity": "number"	
}],
"totalPrice" : "number",
"createdAt":  "string",
}
],
"page" : "number",
"totalPage" : "number"
}
```
- close #119
=> refactor: `GET /v1/orders` API 응답 body 변경

app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
- 장바구니에 들어있는 상품을 제거하는 인수테스트를 작성했습니다.
- resolve #63
=> test: 장바구니 상품 제거 기능 인수테스트 작성

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Cart.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/CannotFindProductInCartException.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java
- 장바구니에서 상품을 제거하는 도메인 메서드를 구현했습니다.
- resolve #63
=> feat: 장바구니 상품 제거 도메인

order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotFindCartException.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java, order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java, order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/CartFixture.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/api/cart/CartConnector.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/CartConnectorService.java, shop/shop-service/src/test/java/shop/woowasap/shop/service/CartConnectorServiceTest.java
cartId와 userId로 장바구니 상품을 주문하는 서비스를 추가했습니다.
- resolve #58
=> feat: 장바구니의 상품 주문 서비스 추가

app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
장바구니 물건 수량 수정 인수테스트 작성했습니다.
- resolve #62
=> test: 장바구니 상품 수량 수정 인수테스트 작성

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/spi/CartRepository.java, shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java, shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
- 장바구니에 있는 상품을 제거하는 서비스를 구현했습니다.
- resolve #63
=> feat: 장바구니 상품 제거 서비스 구현

app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/api/CartApiSupporter.java, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/api/cart/CartUseCase.java, shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java, shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
- 장바구니 상품 제거 컨트롤러를 구현했습니다.
- resolve #63
=> feat: 장바구니 상품 제거 컨트롤러 구현

app/src/test/java/shop/woowasap/accept/AcceptanceTest.java, app/src/test/java/shop/woowasap/accept/AcceptanceTestConfiguration.java, app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java, auth/auth-repository/src/main/java/shop/woowasap/auth/repository/entity/UserEntity.java
인수테스트용 어드민 계정 추가했습니다.
- resolve #150
=> feat: 인수테스트용 어드민 계정 추가

.github/workflows/acceptancetest-analyze.yml
sonarcloud 가 develop에 push됐을때도 수행되도록 수정했습니다.
- close #173
=> chore: sonarcloud 가 develop에 push됐을때도 수행되도록 수정

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/ProductConnector.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/out/ProductRepository.java, shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java, shop/shop-repository/src/main/java/shop/woowasap/shop/repository/jpa/ProductJpaRepository.java, shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java, shop/shop-repository/src/test/java/shop/woowasap/shop/repository/support/ProductFixture.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductConnectorService.java, shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductConnectorServiceTest.java
상품, 카트 구매에 성공하면, 상품 수량이 줄어드는 기능을 추가했습니다.
- #182
=> feat: 주문 성공시 상품 재고 감소 기능 추가

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java, order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderIdResponse.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
주문성공시, `OrderIdResponse` 와 `Ok` 를 반환하도록 수정했습니다.
- resolve #196
=> refactor: 주문성공시 OrderIdResponse와 Ok를 반환하도록 수정

shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java, shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
- Product 전체 조회를 startTime 기준으로 정렬한다
- PageRequest 에 startTime 기준 오름 차순 정렬 추가
- close #178
=> feat: Product 전체 조회를 startTime 기준으로 정렬

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/SaleEndedProductException.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/out/ProductRepository.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java, shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java, shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java, shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
- Product 상세 조회 시, 판매가 끝난 Product 일 경우 예외가 발생하도록 수정한다.
- close #177
=> feat: Product 상세 조회 시, 판매가 끝난 Product 일 경우 예외 발생

app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/fixture/CartFixture.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/response/CartProductResponse.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/CartMapper.java, shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/CartFixture.java
장바구니 상품 Response 에 상품의 남은 재고를 추가했습니다.
- close #180
=> feat: 장바구니 상품 Response 에 상품의 남은 재고 추가

order/order-service/build.gradle, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java, order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
refactor: order 모듈 `Instant.now() -> TimeUtil.now()` 과 같이 변경했습니다.
- close #193
=> refactor: order 모듈 `Instant.now() -> TimeUtil.now()` 로 변경

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java, shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProductQuantity.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/support/CartFixture.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
CartProduct의 수량을 최소 1개 최대 10개로 설정했습니다.
- close #179
=> refactor: CartProduct의 수량을 최소 1개 최대 10개로 설정

order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderConnector.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderConnectorService.java, order/order-service/src/test/java/shop/woowasap/order/service/OrderConnectorServiceTest.java
`OrderConnector` 인터페이스를 구현했습니다.
- close #207
=> feat: `OrderConnector` 인터페이스 구현

app/build.gradle, app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/PayOrderAcceptanceTest.java, app/src/test/java/shop/woowasap/accept/support/api/PayApiSupporter.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/DetailOrderResponse.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java, order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java, order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java, payment/payment-repository/src/main/java/shop/woowasap/payment/repository/PaymentRepositoryImpl.java, payment/payment-repository/src/main/java/shop/woowasap/payment/repository/jpa/PaymentEntityRepository.java, payment/payment-repository/src/test/java/shop/woowasap/payment/repository/PaymentRepositoryImplTest.java
주문 - 결제 검증 테스트를 추가했습니다.
- close #212
=> test: `Order` -> `Payment` 검증 테스트 추가

app/build.gradle, app/src/test/java/shop/woowasap/accept/PayOrderAcceptanceTest.java, coverage-exclude.asap, order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java, order/order-service/src/main/java/shop/woowasap/order/service/config/OrderAsyncConfig.java, payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentEventService.java, payment/payment-service/src/main/java/shop/woowasap/payment/service/config/PaymentAsyncConfig.java
`Async thread, wait queue` count를 설정 했습니다.
- close #214
=> feat: `Async thread, wait queue` count 설정

app/src/main/java/shop/woowasap/advice/GlobalExceptionHandler.java, auth/auth-controller/build.gradle, auth/auth-controller/src/main/java/shop/woowasap/auth/controller/AuthController.java, core/util/src/main/java/shop/woowasap/core/util/web/ErrorTemplate.java, coverage-exclude.asap, order/order-controller/build.gradle, order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java, payment/payment-controller/build.gradle, payment/payment-controller/src/main/java/shop/woowasap/payment/controller/PayController.java, shop/shop-controller/build.gradle, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
ErrorTemplate과 ControllerAdvice 를 부착 했습니다.
- close #235 
- close #238
=> feat: `ErrorTemplate`, `ControllerAdvice` 를 부착

app/src/main/resources/logback-spring.xml, auth/auth-controller/src/main/java/shop/woowasap/auth/controller/AuthController.java, coverage-exclude.asap, order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java, payment/payment-controller/src/main/java/shop/woowasap/payment/controller/PayController.java, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java, shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
`4xx` 번 예외에 대해서, info 로그를 남기도록 설정했습니다.
- close #236
=> chore: `4xx` 번 예외 info 로그 남기게 설정

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/SaleTime.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/SaleTimeTest.java, shop/shop-repository/src/test/java/shop/woowasap/shop/repository/support/ProductFixture.java, shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java, shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
- 상품 판매 시간을 최대 12시간에서 최대 10일로 변경했습니다.
- close #242
=> feat: 상품 판매 시간 변경

order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java, order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/OrderCanceledEvent.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java, payment/payment-domain/src/main/java/shop/woowasap/payment/domain/out/PaymentRepository.java, payment/payment-domain/src/test/java/shop/woowasap/payment/domain/PaymentTest.java, payment/payment-domain/src/test/java/shop/woowasap/payment/domain/support/PaymentFixture.java, payment/payment-repository/src/main/java/shop/woowasap/payment/repository/PaymentRepositoryImpl.java, payment/payment-repository/src/main/java/shop/woowasap/payment/repository/jpa/PaymentEntityRepository.java, payment/payment-repository/src/test/java/shop/woowasap/payment/repository/PaymentRepositoryImplTest.java, payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentEventService.java, payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentService.java, payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentEventServiceTest.java, payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentServiceTest.java, payment/payment-service/src/test/java/shop/woowasap/payment/service/support/PaymentFixture.java
주문과 결제 취소 서비스를 구현했습니다.
- resolve #255
=> feat: `Order` , `Pay` Cancel 서비스를 구현한다

payment/payment-domain/src/main/java/shop/woowasap/payment/domain/in/response/PaymentResponse.java, payment/payment-domain/src/main/java/shop/woowasap/payment/domain/out/PaymentRepository.java, payment/payment-repository/src/main/java/shop/woowasap/payment/repository/PaymentRepositoryImpl.java, payment/payment-repository/src/test/java/shop/woowasap/payment/repository/PaymentRepositoryImplTest.java, payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentService.java, payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentServiceTest.java
=> refactor: 재결제 로직 수정

app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java, order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderResponse.java, order/order-repository/src/main/java/shop/woowasap/order/repository/OrderRepositoryImpl.java, order/order-repository/src/test/java/shop/woowasap/order/repository/OrderRepositoryImplTest.java, order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java, order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java, order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
주문 내역 리스트에서 OrderId 역순으로 정렬 및 주문 타입을 추가했습니다.
- close #276
=> refactor: 주문 내역 리스트에서 OrderId 역순으로 정렬 및 주문 타입 추가

order/order-service/src/main/java/shop/woowasap/order/service/OrderConnectorService.java
`consume stock`에서 `DoesNotOrderedException` 롤백을 방지했습니다.
- close #284
=> fix: `consume stock`에서 `DoesNotOrderedException` 롤백 방지

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProductQuantity.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
Product의 재고가 0인 경우, Cart에 담기는 경우 예외처리 추가했습니다.
- close #287
=> fix: Product의 재고가 0인 경우, Cart에 담기는 경우 예외처리 추가

shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java, shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java, shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java, shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java, shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
- 상품 수정 요청 시, 판매관련 시간인 startTime과 endTime 을 검증하는 로직을 추가했습니다.
- close #291
=> fix: 상품 수정 요청 시, startTime 과 endTime 검증 로직 추가

shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
- 상품이 등록되거나 수정될 때 Redis Cache를 초기화한다
- close #289
=> feat: 상품이 등록되거나 수정될 때 Redis Cache 초기화
